import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  authContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    backgroundColor: '#C6FCFF',
  },
  authHeader: {
    fontSize: 80,
    fontWeight: '600',
    position: 'absolute',
    top: 100,
    color: '#4909A9',
  },
  button: {
    borderWidth: 1,
    backgroundColor: '#69FFB7',
    color: 'black',
    paddingVertical: 20,
    paddingHorizontal: 40,
    fontSize: 20,
    fontWeight: '600',
    margin: 30,
    shadowRadius: 5,
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.2,
  },
  error: {
    backgroundColor: 'pink',
    color: 'black',
    borderWidth: 2,
    fontSize: 20,
    padding: 40,
    position: 'absolute',
    bottom: 100,
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
  },
});
